### ISSUE TITLE
secrets validation and update only looks at targets

### ISSUE THREAD

**Issue by adrianchifor** [deepmind/kapitan#106]
If we have `secrets/common` for example, `kapitan secrets --validate-targets` or `kapitan secrets --update-targets` will ignore it and only look at `secrets/targets/`.

**Comment by ramaro** [comment]
This is by design, not a bug. Secrets need to belong to a target so a recipient list can be fetched per target. Hence the need to be in `secrets/targets`. 

Anything outside of `secrets/targets` won't be a target secret.

**Comment by adrianchifor** [comment]
We can still check outside `targets` and see if a folder is linked to a `class`

**Comment by ramaro** [comment]
Hmm, not sure I understand that use case.

**Comment by adrianchifor** [comment]
Actually you're right, a sensible solution would be to keep everything in the targets, even if duplication occurs, as it allow for customization down the line.

Was thinking of our mysql example, where we have a secret `secrets/mysql/root/password`, it's used in the `mysql` components class, and get it's recipients from `common` class.
