### ISSUE TITLE
Allow configurable indentation for compiled YAML/JSON files

### ISSUE THREAD

**Issue by DWSR** [deepmind/kapitan#109]
https://github.com/deepmind/kapitan/blob/d7ba2af70c954f2f8687286bf3a057f03f2adda4/kapitan/targets.py#L347

**Comment by adrianchifor** [comment]
#110 Will merge tomorrow :)

**Comment by adrianchifor** [comment]
@DWSR Once we merge #125 (for `0.17.1`), you should be able to configure a default indent value in `.kapitan` like:
```
version: 0.17.1
compile:
  indent: 4
```
