### ISSUE TITLE
create kapitan binary (using pyinstaller or similar)

### ISSUE THREAD

**Issue by ramaro** [deepmind/kapitan#145]

**Comment by rohitsanjay** [comment]
This seems interesting to me. I would like to work on this project as part of gsoc. It would be helpful if you throw some more insight into this project.

**Comment by uberspot** [comment]
Ramaro has a test branch with some initial implementation of this https://github.com/ramaro/kapitan/tree/cython_build 
The goal is to get automated binaries of kapitan that can be easily deployed anywhere. 
Minimal maintenance is desired. All build artifacts should be auto-tested and released on github as well.

**Comment by rohitsanjay** [comment]
@uberspot Thanks , I will look into it and report my progress.

**Comment by yoshi-1224** [comment]
Just curious because I'm also interested in this project: do we intend to Cythonize the code before converting it into binary/one-folder using pyinstaller or something similar?

**Comment by ramaro** [comment]
That's the idea.
