### ISSUE TITLE
GPG encrypt passes binary blob to secrets_file['data'] instead of base64

### ISSUE THREAD

**Issue by adrianchifor** [deepmind/kapitan#150]
`kapitan secrets --write/--update/--update-targets ...` does not base64 the encrypted data from secrets, instead it writes the encrypted binary blob directly to yaml:
```
data: !!binary |
...
```

**Comment by theinrichs** [comment]
@adrianchifor 
Is this really fixed? I just tested kapitan 0.19.0 update-targets and the secrets still have
```
data: !!binary |
  hQIMA3wpiKskwq5cARAAyaxFH4kfy6nn5wYEkSv7vmhZ1b32nLrXXRCJgGL2EbA85kj3ixb8GiOz
```
When you try `kapitan compile --reveal`
you get

```
kapitan.refs.secrets.gpg.GPGError: no data was provided
```

**Comment by ramaro** [comment]
@theinrichs was your secret created before 0.19.0?

**Comment by ramaro** [comment]
`data:` should be not be !!binary - that was a bug introduced in master but I don't think it was ever part of a release. I can compile --reveal my pre 0.19.0 just fine.

**Comment by adrianchifor** [comment]
Still happening on --update/--update-targets
