### ISSUE TITLE
Simpler Example

### ISSUE THREAD

**Issue by manhof** [deepmind/kapitan#151]
It may be useful to do a simpler example for kaptian, something like a helloworld/hostname example that builds for multiple namespaces with a cluster.

**Comment by uberspot** [comment]
Just for reference, there are some examples also available here https://github.com/ramaro/kapitan-examples/ in case it helps anybody.

**Comment by harsh-98** [comment]
@uberspot I have use https://github.com/ramaro/kapitan-examples/. I would like to work on this.
