### ISSUE TITLE
Validate compile operation using jsonschema lib

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#194]
Have kapitan use the jsonschema lib (if you enable it in your inventory). 
jsonschema lib will validate the compiled file output structure for k8s/terraform/whatever other yaml resources.
links:
https://json-schema.org/implementations.html
https://pypi.org/project/jsonschema/

**Comment by pranavgupta1234** [comment]
Hi @uberspot , I would love to work on this issue under GSOC 2019. I have started exploring the Kapitan source and it would be great if you can point me in some specific direction to begin with.

**Comment by pranavgupta1234** [comment]
Hey @uberspot, what tasks are involved in validating the file output structure ? Currently I think that we are required to define a jsonschema which will define properties for compiled files like their type, location, etc.
