### ISSUE TITLE
Integrate ksonnet projects to kapitan

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#195]
aka write a tool to import a ksonnet project to kapitan

**Comment by sh0rez** [comment]
More relevant right now as ksonnet got deprecated ksonnet/ksonnet/pull/914

**Comment by adrianchifor** [comment]
Ksonnet/Jsonnet libraries can just be imported using [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler) and add `--search-paths vendor` to `kapitan compile` to make the libs visible.
