### ISSUE TITLE
Allow setting inventory values based on custom commands

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#197]
Possible example, but the format of the inventory is flexible, you can use whatever is better. 
```
parameters:
  name: "something"
  service_account:  ?{exec: "gcloud iam service-accounts create [SA-NAME] --display-name "[SA-DISPLAY-NAME]" }
```
And the output would be saved/cached somewhere.

**Comment by ramaro** [comment]
I think this needs a bit more discussion on the user experience. Does it make sense to use/abuse the secrets system for such feature? Is an `exec` type really necessary? Should it be a function instead?

**Comment by ramaro** [comment]
I also think the best solution is actually to allow the user to define custom functions for their templates

**Comment by harsh-98** [comment]
@uberspot . Exec feature can also be abused. Like running some malicious command. Though we can put some checks that only specific commands are allowed like in  `eval_func`  . https://github.com/deepmind/kapitan/blob/master/kapitan/refs/functions.py#L30

**Comment by uberspot** [comment]
Those malicious commands will have to be coming from the developers themselves I assume. 
We could start with a list of allowed commands but sanitizing these seems like extra effort to restrict the developers themselves. Kapitan isn't meant to handle external/unsanitised  user input anyway. It's a templating tool.

**Comment by ramaro** [comment]
Let's close this and work on allowing custom functions instead?

**Comment by uberspot** [comment]
:+1: closing
