### ISSUE TITLE
Restructure/simplify readme

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#198]
The README needs some work. 
- simplifying examples and explanations, 
- restructuring it to multiple smaller files to make reading easier
- removing duplicate phrases/noise
- making sure the gh-pages (https://kapitan.dev/ ) also works and looks nice.

**Comment by uberspot** [comment]
Use https://squidfunk.github.io/mkdocs-material/getting-started/ as part of the above work.

**Comment by vaibhavk** [comment]
I would like to work on this, would share the structure of docs that I propose

**Comment by yoshi-1224** [comment]
Hi @vaibhavk. 
How is your progress on this issue? Having noticed that you are also working on the integration with Vault, I thought I could help out for this. This is actually relevant to me as well in that I would like to contribute some guided examples on the new features too. Let me know your thoughts!

**Comment by vaibhavk** [comment]
@yoshi-1224 I haven't made any progress on this issue yet. You can go ahead with your structure. 
The vault feature is self documented in the KAP-6 so just have to add all that in the feature examples when it's merged.
