### ISSUE TITLE
Add tests for secrets

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#208]
The following secrets functionality is missing from tests:

 - update targets
 - validate targets
 - aws kms backend
 - gkms backend

**Comment by adrianchifor** [comment]
https://github.com/deepmind/kapitan/pull/236 covers `--validate-targets` and [aws/g]kms flow.

**Comment by adrianchifor** [comment]
The only one remaining is more coverage for update targets, which we have for GPG but not KMS as we can't mock the updates from the APIs. Let's open another issue just for update targets for KMS.
