### ISSUE TITLE
Allow defining custom jinja2 filters in templates

### ISSUE THREAD

**Issue by ramaro** [deepmind/kapitan#237]
**Allow defining custom jinja2 filters in templates**

We now have more jinja2 filters (thanks to @adrianchifor work on #234). However I'd like support for providing a custom python file with more filters, e.g.:

```
$ kapitan compile --jinja2-filters=lib/jinja2_filters.py
```
The default behaviour should be for Kapitan not to error should the default jinja2 filters file not exist. 

Should it exist, Kapitan will first import those filters into jinja2's internal env settings.

(A better default file name other than one in the example should be discussed)

**Comment by pranavgupta1234** [comment]
Hey @ramaro , I am planning to work on this issue. The execution plan can be to use [importlib](https://docs.python.org/2/library/importlib.html#importlib.import_module) to dynamically import the custom filter module specified by user and then define one more function "load_jinja2_filters_from_file" to import the functions and suppy them in env. We can extract the name for function but then the exposed name of filter will be same as the original name.
