### ISSUE TITLE
Document the Kadet input

### ISSUE THREAD

**Issue by th31nitiate** [deepmind/kapitan#255]
I apologize as this is just a request for an understanding of what Kadet is and how it functions?

I am trying to gain a better understanding as to when using the dev version I am able to init a directory with examples, but it is not very clear as to the function.

It looks like a method to perform inventory from python scripts but this is not clear.

**Comment by ramaro** [comment]
Kadet is undocumented on purpose because it is experimental. But have a read of  https://github.com/deepmind/kapitan/pull/190 and you'll get a feel of what it currently does.

**Comment by uberspot** [comment]
I changed the ticket to track documenting the feature in the future.
