### ISSUE TITLE
Remote URLs in jsonnet imports

### ISSUE THREAD

**Issue by drzero42** [deepmind/kapitan#260]
kubecfg has implemented the ability to do import and importstr on URLs, making it possible to import libraries and JSON/YAML (if combined with #259) from remote sources.
This would make it possible to import an upstream YAML and output a modified version, giving Kustomize a run for it's money with the power that jsonnet brings to the table. See something like [kustomize-libsonnet](https://github.com/anguslees/kustomize-libsonnet) for examples of how this could be used (only currently possible with kubecfg).

**Comment by harsh-98** [comment]
@uberspot I will start working on this one, as #263 is merged. And will also do the suggested changes in other open PRs.

**Comment by adrianchifor** [comment]
This should be done as part of dependency management (https://github.com/deepmind/kapitan/issues/91) and not in jsonnet. We don't want to block compile every time to download and load files.
