### ISSUE TITLE
Create terraform lib in python for Kadet

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#271]
Following #191 create a python lib for terraform's most common operations (in the same spirit of kube.libjsonnet) using the new kadet/python input type.

**Comment by Cyanopus** [comment]
@uberspot I was reading over and interested in how would this look like and the use case. Can you share some info?

**Comment by uberspot** [comment]
The idea behind it was to create a jsonnet library with most common resources that could be created with terraform but abstracted in a function. So that people can re-use them with ease. 
But after thinking about this for a while, it might just make more sense to add more jsonnet terraform examples instead since that's what people would use.
I can add some example templates for google cloud resources by the end of this week and see if it helps. :)
