### ISSUE TITLE
Add ability to specify custom extension in inventory

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#276]
Following https://github.com/roboll/helmfile/issues/565 
It makes sense to allow custom extensions for inventory files (yml or yaml) to make kapitan more flexible. :)

**Comment by adrianchifor** [comment]
Inventory files are interpreted by reclass. Relevant TODO https://github.com/salt-formulas/reclass/blob/develop/doc/source/todo.rst#configurable-file-extension.

We could make an MR to update `reclass/storage/yaml_fs/__init__.py` and `reclass/storage/yaml_fs/directory.py` as it hardcodes `FILE_EXTENSION = '.yml'`.

**Comment by pranavgupta1234** [comment]
I would like to take up this issue. Should I open an corresponding issue on https://github.com/salt-formulas/reclass ?

**Comment by uberspot** [comment]
Go for it. We could also make a PR in kapitan to update reclass if it's not breaking.

**Comment by pranavgupta1234** [comment]
Ref : https://github.com/salt-formulas/reclass/pull/85

**Comment by pranavgupta1234** [comment]
@uberspot https://github.com/salt-formulas/reclass/pull/85 is merged now.

**Comment by uberspot** [comment]
Wonderful! :) They haven't pushed a new release though so I doubt we can upgrade reclass at the moment unless we maintain our own mirror. :/ 
Also this regression still remains https://github.com/salt-formulas/reclass/issues/84

**Comment by adrianchifor** [comment]
For visibility, we are waiting for https://github.com/salt-formulas/reclass/pull/87 to be merged and for reclass to make a new release.

**Comment by uberspot** [comment]
This has now been added in kapitan 0.27.3 after forking and updating our usage of reclass. :) 
Closing as done.
