### ISSUE TITLE
Terraform example projects are missing rendered kubernetes.tf.json after compilation

### ISSUE THREAD

**Issue by sclausson** [deepmind/kapitan#278]
**kubernetes.tf.json not rendered for terraform example projects**
`examples/terraform/compiled/project2/terraform` and `examples/terraform/compiled/project3/terraform` are missing `kubernetes.tf.json` 

**To Reproduce**
1. `cd examples/terraform`
2. `kapitan compile`

**Expected result**
```
$ tree compiled/project2
compiled/project2
├── scripts
│   └── terraform.sh
└── terraform
    ├── kubernetes.tf.json
    ├── output.tf.json
    └── provider.tf.json
```

**Actual result**
```
$ tree compiled/project2
compiled/project2
├── scripts
│   └── terraform.sh
└── terraform
    ├── output.tf.json
    └── provider.tf.json
```

**Comment by uberspot** [comment]
Closing as fixed :+1:
