### ISSUE TITLE
Kapitan Example

### ISSUE THREAD

**Issue by kapilgarg83** [deepmind/kapitan#303]
Hi,

I am new to KAPITAN,

Example given in very advance.. Can anybody help by giving some simple and good example to call kube.libjsonnet file.
I want to make a deployment with PersistentVolume

Thanks

**Comment by vaibhavk** [comment]
Hi @kapilgarg83, you can have a look at [ramaro's kapitan-examples](https://github.com/ramaro/kapitan-examplesl), or for `kube.libjsonnet` you can have a look at [this repository](https://github.com/richardfelkl/kapitans-fleet), it contains Kapitan templates for Kubernetes services.

**Comment by kapilgarg83** [comment]
Thanks a lot Vaibhav.


Thanks & Regards
Kapil Garg
