### ISSUE TITLE
Conditional Output 

### ISSUE THREAD

**Issue by kapilgarg83** [deepmind/kapitan#321]
Hi,

I need to generate an output base on some conditions 
for example:

My_deployment: if (server.env_name == "dev") then .airflowredisDeployment(server.deployment.name) else{ },

Problem is in case of else it generate blank yml file.. and which throw error when we deply on cluster using apply.sh.

my requirement if I did not want to generate output file in case of else condition.
Kindly suggest

**Comment by uberspot** [comment]
Split what you are generating to a separate file. 
Use a main.jsonnet file to import the separate files and output those via kapitan.
Put the if statement in that main.jsonnet file and basically only output the extra files if that statement is true.

**Comment by uberspot** [comment]
Example of main.jsonnet:
```
local deployment = import "./deployment.jsonnet";
local configmap = import "./configmap.jsonnet";
local service = import "./service.jsonnet";

{
 my_configmap: configmap,
 my_deployment: deployment,
 [if some_condition then "my_service"]: service,
}

```
