### ISSUE TITLE
KAP-5 - Implement plain ref type, revamp secrets into refs

### ISSUE THREAD

**Issue by ramaro** [deepmind/kapitan#333]
See [KAP-5](https://github.com/deepmind/kapitan/blob/master/docs/kap_proposals/kap_5_ref_types_redesign.md)

**Comment by uberspot** [comment]
This has been fixed in code, but needs to be announced in all kapitan channels when the feature reaches a non-rc build.

**Comment by ramaro** [comment]
all done since 0.25
