### ISSUE TITLE
Kapitan in GCloud Run

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#343]
Something we could do: https://twitter.com/ahmetb/status/1164214096033529856?s=09

**Comment by prakashrj** [comment]
How can Kapitan deploy a service like GCloud run, when it can only generate compiled output?

**Comment by uberspot** [comment]
The idea behind this issue is to have kapitan run as a binary/docker image in GCloud run so that people can use kapitan without installing it, via GCloud Run. :) It's not meant to deploy to gcloud run.

**Comment by viveksonar** [comment]
So the main idea will be to create a dockerfile and build a container image and directly deploy it in cloud shell! Right?

**Comment by uberspot** [comment]
Sorry i forgot to close this a while ago.
