### ISSUE TITLE
Using Kapitan to generate Terraform configuration

### ISSUE THREAD

**Issue by atrakic** [deepmind/kapitan#350]
**Describe the bug/feature**
There is no manifests directory as explained at examples/terraform/README.md so I cannot figure out how to use compiled file with TF. 

**To Reproduce**
1. Go to examples/terraform
2. `ls` 
3. no manifests directory found

**Expected behavior**
$ See README.md as above.

**Screenshots**
If applicable, add screenshots to help explain your problem/idea.

** If it's a bug (please complete the following information):**
 - `python --version`:
 - `pip3 --version`: 
 - `Are you using pyenv or virtualenv?`

**Additional context**

**Comment by ramaro** [comment]
Thanks for reporting @atrakic 

By `manifests` we mean the files you will find in the `compiled/` directory. For example, for `project1`, you will see all the terraform "manifests" in `examples/terraform/compiled/project1`

**Comment by uberspot** [comment]
Readme addressed here https://github.com/deepmind/kapitan/pull/352 :) 
Thanks for reporting. If you see more feel free to open new issues/PRs.
