### ISSUE TITLE
Invalid choice "apply" flag

### ISSUE THREAD

**Issue by atrakic** [deepmind/kapitan#351]
**Describe the bug/feature**
According to https://kapitan.dev/#quickstart shows apply flag which is not found on 0.23.1 

**To Reproduce**
1. do: $ kaptain
2. no apply flag on help either 
3. doesnt match quickstart.md

**Expected behavior**
Apply flag should be found. 

**Screenshots**
If applicable, add screenshots to help explain your problem/idea.

** If it's a bug (please complete the following information):**
 - `python --version`:
Python 3.6.8
 - `pip3 --version`:
 
 - `Are you using pyenv or virtualenv?`
no

**Additional context**

**Comment by yoshi-1224** [comment]
Hi,

Could you possibly be confused with kubectl apply?

**Comment by ramaro** [comment]
There's no `apply` command in Kapitan :)

**Comment by atrakic** [comment]
Yep my bad. Sorry for disturb. Closing from here.
