### ISSUE TITLE
JSONNET not resolving refs when using std function

### ISSUE THREAD

**Issue by shauryagarg2006** [deepmind/kapitan#393]
In inventory file I have attributes like:

```
parameters:
    sitesecret:
        name: ?{plain:data_base_name}
```

Then in the components I am referring to them like this:

```
local kap = import 'lib/kapitan.libjsonnet';
local kube = import 'lib/kube.libsonnet';
local inventory = kap.inventory();

{
  'site-secret': {
      'this_works': inventory.parameters.sitesecret.name,
      'this_does_not_work': std.base64(inventory.parameters.sitesecret.name),
    }
}
```

The value which the is getting pulled in the kapitan compile is base64 of `?{plain:data_base_name}` and not the value stored in the ref when using the std library function.

Is there any problem in my approach?

**Comment by adrianchifor** [comment]
Compile doesn't reveal the value of a secret, it just fills in the reference with a hash. What you're looking for is something like:
```
parameters:
    sitesecret:
        name: ?{plain:data_base_name_b64|reveal:data_base_name|base64}
```
The reveals the original value and auto-creates a new base64 encoded secret. Finally you just `kapitan refs --reveal <your compiled file with reference>`.

**Comment by ramaro** [comment]
What @adrianchifor is correct. The only correction I'd make is that plain refs don't compile to hashed tags and will reveal by default. 
Read more at https://github.com/deepmind/kapitan/blob/master/docs/kap_proposals/kap_5_ref_types_redesign.md

**Comment by shauryagarg2006** [comment]
Thanks for the quick response.
