### ISSUE TITLE
Cannot kapitan compile --cache when a compiled/.kapitan_cache file is present.

### ISSUE THREAD

**Issue by jperville** [deepmind/kapitan#395]
**Describe the bug/feature**

Cannot `kapitan compile --cache` when a `compiled/.kapitan_cache` file is present.

**To Reproduce**
1. cd to a sample kapitan project
2. ls -l compiled/.kapitan_cache  (should not list anything)
3. run `kapitan compile --cache .` (should run successfully the first time)
4. ls -l compiled/.kapitan_cache  (should list a kapitan_cache file)
5. run `kapitan compile --cache .` again (should fail with error "ValueError: Pool is still running")

**Expected behavior**

`kapitan compile --cache` should be successful on any run,
and not only when the `compiled/.kapitan_cache` is not present.

If it's a bug (please complete the following information):
 - `python --version`: Python 3.7.4
 - `pip3 --version`: pip 19.2.3 from /opt/venv/lib/python3.7/site-packages/pip (python 3.7)

**Additional context**

Using `deepmind/kapitan:latest` docker image, which as of 2019-10-14 uses kapitan 0.25.0-rc.2

I run dockerized kapitan with the following wrapper script:
```
#!/bin/sh
exec \
  docker run -t --rm \
    -u $(id -u):$(id -g) \
    -e http_proxy=${http_proxy} \
    -e https_proxy=${https_proxy} \
    -e no_proxy=${no_proxy} \
    -v $(pwd):/src:delegated \
    deepmind/kapitan \
    "${@}"
```

Output of `kapitan compile --cache` on my workstation:
```
No changes since last compilation.
Traceback (most recent call last):
  File "/opt/venv/bin/kapitan", line 11, in <module>
    load_entry_point('kapitan==0.25.0rc2', 'console_scripts', 'kapitan')()
  File "/opt/venv/lib/python3.7/site-packages/kapitan/cli.py", line 332, in main
    jinja2_filters=args.jinja2_filters)
  File "/opt/venv/lib/python3.7/site-packages/kapitan/targets.py", line 137, in compile_targets
    pool.join()
  File "/usr/local/lib/python3.7/multiprocessing/pool.py", line 553, in join
    raise ValueError("Pool is still running")
ValueError: Pool is still running
```

**Comment by adrianchifor** [comment]
Good spot, thanks for raising it. Made a PR which should fix this. We will release another RC later this week.

**Comment by jperville** [comment]
Thank you for the quick fix @adrianchifor .
