### ISSUE TITLE
Helm charts with subcharts may clobber output.  Istio chart broken

### ISSUE THREAD

**Issue by calvinmorrow** [deepmind/kapitan#417]
**Edit**
The bug below looks like it was fixed in a later Kapitan helm library release.  Subcharts are output to multiple directories when using the latest binary release, but with my older pip release exhibit the bug below.  Updating the pip release doesn't necessarily update the helm code so there's a possibility for some behavioral variation depending on when the helm support was compiled.

**Describe the bug/feature**
A helm chart which contains multiple subcharts may clobber output due to having multiple templates with the same name (ie: deployment.yaml).  Since each subchart is processed individually and output to a single directory, only the last chart run will be output.

**To Reproduce**
1) Create a class using a chart with multiple subcharts embedded (testing against https://storage.googleapis.com/istio-release/releases/1.3.3/charts/istio-1.3.3.tgz) and unpack it.
2) Compile

**Expected behavior**
Either:
1) Output each subchart into its own file
  or
2) Concatenate output so the previous output is not lost

**Comment by ramaro** [comment]
@calvinmorrow not an issue?

**Comment by calvinmorrow** [comment]
Not an issue anymore.  Looks like the behavior was due to me using an older version of the Kapitan helm lib which has since been fixed.
