### ISSUE TITLE
Change compile documentation for jinja

### ISSUE THREAD

**Issue by omkarprabhu-98** [deepmind/kapitan#462]
**Describe the bug**
[Kapitan compile](https://kapitan.dev/compile/) documentation mentions `jinja` as a possible value in the `input_type` (screenshot 1). However, this gives an error on the compilation as shown in screenshot 2 below

**To Reproduce**
1. Use `jinja` as the `input_type`  in a target
2. Compile using `docker run -it --rm -v $(pwd):/src:delegated deepmind/kapitan compile`
4. See error as in screenshot 2

**Expected behavior**
Fix: Documentation should mention `jinja2` as the value for the `input_type` field instead of `jinja`.

**Screenshots**
1) Documentation [Kapitan compile](https://kapitan.dev/compile/)
![compile_doc](https://user-images.githubusercontent.com/23053768/75113335-1f9f9000-5673-11ea-8194-55ae8e1b570c.PNG)

2) Error encountered 
![error](https://user-images.githubusercontent.com/23053768/75113339-21695380-5673-11ea-9b85-4fe0c450048c.PNG)

- Using the docker image of Kapitan

**Additional comments**
If possible, can I change this?

**Comment by ramaro** [comment]
Thanks for reporting. Can you please share the snippet of code that caused that issue? Also the output of  `$ kapitan --version`

**Comment by omkarprabhu-98** [comment]
1) Code snippet
![code](https://user-images.githubusercontent.com/23053768/75116176-a6606700-568b-11ea-86b2-371007b6ad1e.PNG)

2) Kapitan version
`$ docker run -it --rm -v $(pwd):/src:delegated deepmind/kapitan --version` => 0.27.0
![version width="40%"](https://user-images.githubusercontent.com/23053768/75116218-0820d100-568c-11ea-82ad-6e9424135e54.PNG)



Is this fine?
