### ISSUE TITLE
Updating kapitan.dev/secrets/

### ISSUE THREAD

**Issue by AlphaRoy14** [deepmind/kapitan#471]
**Describe the bug/feature**

Hi! The [kapitan.dev/secrets/](https://kapitan.dev/secrets/) page promotes the use of `kapitan secrets` instead of `kapitan refs` as  shown in [docs/secrets.md](https://github.com/deepmind/kapitan/blob/master/docs/secrets.md). I believe to fix it `mkdocs gh-deploy -b gh-pages` should suffice.

**Comment by adrianchifor** [comment]
Good point, just pushed https://github.com/deepmind/kapitan/commit/196ce5d1e865bba94e757942b9e94fe7ec06c8a4 and kapitan.dev should now be up-to-date. Thanks!
