### ISSUE TITLE
Investigate usage with SELINUX policies

### ISSUE THREAD

**Issue by th31nitiate** [deepmind/kapitan#496]
I don't use slack yet. I am just posting this for discussion or thought at present.

SELINUX is a security mechanism used to authorise system calls and other things on Cent OS systems. It is most useful when used to create profiles for specific applications or containers.

I prefer using Nomad when running containers. In such cases where name spacing or other security enhancements may not be available. It is useful to utilise such tools. 

Since SELINUX policies can use JSON would it be possible or useful to have such an implementation. 

This would mean using Kapitan to generate policies or to group security concerns into components. 

I am not entirely familiar with the usage of SELINUX and I understand that most people do not like it. To be honest due to the environment I have never fully had to consider it. I think it might be a cool thing to detail some where else though.

I would like to get peoples opinions or thoughts on this matter.

**Comment by uberspot** [comment]
It wouldn't hurt to add an (small) example selinux policy generation under the `examples/`. Given that it doesn't have that many differences from other json file generation (like terraform) I'm not sure if I'd add other docs regarding this. An example would be nice though. :)

**Comment by th31nitiate** [comment]
That is great to hear and I may add that. I think at this point it is still kind of a theory. I am wondering if it would be a good use case. 

I would not want to add saturation to the uses for this tool, however considering Android supports SELINUX we can increase the possible use cases.

**Comment by th31nitiate** [comment]
I looked this over and I noticed that SELINUX does not support JSON. I initially thought that it did but I was greatly mistaken. I don't believe this would be the best use case at present. I will close this out for now.

@uberspot  great talk the day it was delivered very well & clearly conceptualised kapitan
