### ISSUE TITLE
Running `init` with the binary does not work

### ISSUE THREAD

**Issue by madonius** [deepmind/kapitan#513]
When I run `kapitan init` with the binary downloaded from the releases, the execution halts with an error.

**To Reproduce**
1. Go to https://github.com/deepmind/kapitan/releases
2. Download latest release `v0.27.3-rc.2`:
3. Execute `kapitan-linux-amd64`
4. Receive an execution error
```bash
$ > wget https://github.com/deepmind/kapitan/releases/download/v0.27.3-rc.2/kapitan-linux-amd64
$ > chmod a+x kapitan-linux-amd64 
$ > ./kapitan-linux-amd64 init
Traceback (most recent call last):
  File "kapitan/__main__.py", line 10, in <module>
  File "kapitan/cli.py", line 533, in main
  File "kapitan/initialiser.py", line 26, in initialise_skeleton
  File "distutils/dir_util.py", line 124, in copy_tree
distutils.errors.DistutilsFileError: cannot copy tree '/tmp/_MEI8BuDFA/kapitan/inputs/templates': not a directory
[85375] Failed to execute script __main__
```

**Expected behaviour**
kapitan initialises the directory

** If it's a bug (please complete the following information):**
 - `python --version`: Python 3.8.3rc1
 - `pip3 --version`: pip 20.1 from /usr/lib/python3/dist-packages/pip (python 3.8)
 - `Are you using pyenv or virtualenv?` no

**Comment by uberspot** [comment]
Fixed in v0.27.3-rc.3  :) Thanks for reporting.
