### ISSUE TITLE
kapitan:ci Docker image issue 

### ISSUE THREAD

**Issue by gobbledygook88** [deepmind/kapitan#552]
**Describe the bug/feature**
The latest `deepmind/kapitan:ci` Docker image (as of writing) appears to be broken. 
`sha256:acaa1ca6541e90c4b26cec218b4e5ccbfb954a9d6337587d802f39ee2a0efa06`
Running `--version`, or any other command, gives the following stacktrace

```
$ kapitan --version
Traceback (most recent call last):
  File "/opt/venv/bin/kapitan", line 5, in <module>
    from kapitan.cli import main
  File "/opt/venv/lib/python3.7/site-packages/kapitan/cli.py", line 23, in <module>
    from kapitan.refs.cmd_parser import handle_refs_command
  File "/opt/venv/lib/python3.7/site-packages/kapitan/refs/cmd_parser.py", line 16, in <module>
    from kapitan.resources import inventory_reclass
  File "/opt/venv/lib/python3.7/site-packages/kapitan/resources.py", line 28, in <module>
    import reclass
ModuleNotFoundError: No module named 'reclass'
```

**To Reproduce**
1. `docker pull deepmind/kapitan:ci`
2. `docker run -it --rm deepmind/kapitan:ci kapitan --version`

**Expected behavior**
Version information to be printed

e.g. when using a previous version
```
$ docker run -it --rm deepmind/kapitan:0.28.1-ci kapitan --version
0.28.1-rc.1
```

**Comment by ramaro** [comment]
Hey, thanks for reporting. We'll have a look.

**Comment by uberspot** [comment]
Sorry about that, I was testing the new github action for building the docker images ( https://github.com/deepmind/kapitan/pull/551 ) , and had to test with the "ci" tag as well.
But you caught a very early bug (I forgot to checkout git submodules in the CI job) and I just fixed the image now. :) 
Thanks for reporting. :+1:
