### ISSUE TITLE
Rename remote inventory key to `inventory` instead of `inventories`

### ISSUE THREAD

**Issue by ramaro** [deepmind/kapitan#570]
The inventory in https://github.com/deepmind/kapitan/blob/master/kapitan/remoteinventory/fetch.py#L34 is set to `inventories` key, however [KAP-7](https://github.com/deepmind/kapitan/blob/master/docs/kap_proposals/kap_7_remote_inventory.md) documents `inventory`. 

Let's keep it consistent and rename to `inventory`.

**Comment by ramaro** [comment]
cc @AlphaRoy14

**Comment by AlphaRoy14** [comment]
Hi @ramaro I was wondering if it would make more sense if we change the doc instead to `inventories` as we use `dependencies` key to specify dependencies and it also indicates that we can specify multiple items?
https://github.com/deepmind/kapitan/blob/master/docs/kap_proposals/kap_1_external_dependencies.md#specification

**Comment by ramaro** [comment]
Fair point. But `dependencies` is a new term in Kapitan, however `inventories` is not as we already have `inventory` in flags, etc... So it makes sense to keep it that way.
