### ISSUE TITLE
Improve debugging

### ISSUE THREAD

**Issue by ademariag** [deepmind/kapitan#62]
When jsonnet fails to compile, the output does not easily allow to understand which target caused the jsonnet to fail.

```
Compiled working-target1 (1.86s)
Compiled working-target2 (1.86s)
Jsonnet error: failed to compile repository/components/cloudsql-proxy/main.jsonnet:
 RUNTIME ERROR: field does not exist: cloudsql
        repository/components/cloudsql-proxy/main.jsonnet:13:26-49       object <anonymous>
```

One possible solution is to write the target being compiled before attempting the compilation. Output could look like this

```
Compiling working-target1  (OK 1.86s)
Compiling working-target2  (OK 1.86s)
Compiling failing-target3
Jsonnet error: failed to compile repository/components/cloudsql-proxy/main.jsonnet:
 RUNTIME ERROR: field does not exist: cloudsql
        repository/components/cloudsql-proxy/main.jsonnet:13:26-49       object <anonymous>
```

**Comment by adrianchifor** [comment]
Should we close #43 in favour of this?

**Comment by ademariag** [comment]
Didn't realize it was there already. It's the same really. Feel free to close this and don't feel constraint by my sample output ;)

**Comment by gburiola** [comment]
The problem with writing the target before starting the compilation is that the app is multithreaded, so you'll see 4 (default number of threads) in flight compilations
