### ISSUE TITLE
Create "cleartext" backend for secrets

### ISSUE THREAD

**Issue by ademariag** [deepmind/kapitan#80]
Secrets with GPG and especially automatic generation of secrets is very powerful.

However for some low-security setups (i.e. minikube or example folder) a user is required to have configured GPG and have the right key to decrypt secrets.

This forces the user to 2 choices:
1) reveal the secret in plaintext by overriding the target file
2) store a "shared" gpg key in the repository to allow for low security situations

The first option will force users to have alternative setups for demo/personal and prod environments
The second option will still force the user to setup gpg, and make more difficult to understand if an encrypted key is "unsecure" and auditing

I would like to encourage a healthy use of secrets that does not force users to diverge from the standard way for convenience.

My proposal is to create a new backend as an alternative to the gpg backend: a **plaintext** secret.

This enfoces a similar workflow but proving the benefit of a gpg-less setup.

Also, explicit use of this backend are easier to audit

example:

`?{gpg:targets/prod/mysql/my_user_password}`

`?{plain:targets/example/mysql/my_user_password}`

ultimately this can easily be templated with 

`?{${encryption_backend}:targets/${target_name}/mysql/my_user_password}`

**Comment by adrianchifor** [comment]
This is now possible with the `?{ref:file/path}` backend.

**Comment by ramaro** [comment]
As of KAP-5, this is now `?{base64:file/path}`
