### ISSUE TITLE
How to generate duplicated keys?

### ISSUE THREAD

**Issue by axot** [deepmind/kapitan#96]
I want to generate `google_iam_policy` for terraform, here is a sample code.

```
data "google_iam_policy" "admin" {
  binding {
    role = "roles/compute.instanceAdmin"

    members = [
      "serviceAccount:your-custom-sa@your-project.iam.gserviceaccount.com",
    ]
  }

  binding {
    role = "roles/storage.objectViewer"

    members = [
      "user:jane@example.com",
    ]
  }
}
```

How to generate two `binding` sections with different values?
Thank you.

**Comment by gburiola** [comment]
Hey @axot.

When converting HCL to JSON, `binding` becomes an array with 2 objects:

```
{
  "data": [
    {
      "google_iam_policy": [
        {
          "admin": [
            {
              "binding": [
                {
                  "members": [
                    "serviceAccount:your-custom-sa@your-project.iam.gserviceaccount.com"
                  ],
                  "role": "roles/compute.instanceAdmin"
                },
                {
                  "members": [
                    "user:jane@example.com"
                  ],
                  "role": "roles/storage.objectViewer"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

There are some good HCL to JSON converters on github. If you just want to convert small snippets of code you can use https://www.hcl2json.com/

**Comment by axot** [comment]
@gburiola Thanks for your advice! After some tries, it almost works now, one problem here now is the compiled json file will escape role's `/` to `\/`, this makes terraform get an error `Error: Error parsing iam.tf.json: 16:31: illegal char escape`.

**Comment by axot** [comment]
It seems this issue was fixed by this commit, https://github.com/deepmind/kapitan/commit/25abab3628a6c2070e0ce7dedc2b9046ccf90457

Thank you.
